import { hashSync } from 'bcrypt-ts-edge';

const sampleData = {
    users: [
        {
            name: "John",
            email: "admin@example.com",
            password: hashSync('123456', 10),
            role: "admin"
        },
        {
            name: "Jane",
            email: "user@example.com",
            password: hashSync('123456', 10),
            role: "user"
        }
    ],
    products: [
        {
            name: "Polo Sporting Stretch Shirt Tomato",
            slug: "polo-sporting-stretch-shirt-tomato",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "49.99",
            brand: "Polo",
            rating: "4.6",
            numReviews: 10,
            stock: 10,
            isFeatured: true,
            banner: "banner-1.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt Red",
            slug: "polo-sporting-stretch-shirt-red",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.png",
                "/images/sample-products/p1-2.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 15,
            isFeatured: true,
            banner: "banner-5.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt Blue",
            slug: "polo-sporting-stretch-shirt-blue",
            category: "Men's Dress Shirt Blue",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "89.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 0,
            isFeatured: true,
            banner: "banner-2.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt green blue",
            slug: "polo-sporting-stretch-shirt-green-blue",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 20,
            isFeatured: true,
            banner: "banner-1.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt green",
            slug: "polo-sporting-stretch-shirt-green123",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 25,
            isFeatured: true,
            banner: "banner-3.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt dark",
            slug: "polo-sporting-stretch-shirt-dark",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 45,
            isFeatured: true,
            banner: "banner-4.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt red dark",
            slug: "polo-sporting-stretch-shirt-red-dark",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.png",
                "/images/sample-products/p1-2.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 2,
            isFeatured: true,
            banner: "banner-5.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt green dark",
            slug: "polo-sporting-stretch-shirt-green-dark",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-4.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt Green",
            slug: "polo-sporting-stretch-shirt-green",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-3.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt yellow dark",
            slug: "polo-sporting-stretch-shirt-yellow-dark",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-2.jpg",
        },
    ]
}

export default sampleData;