const sampleData = {
    products: [
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.jpg",
                "/images/sample-products/p1-1.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-1.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.jpg",
                "/images/sample-products/p1-2.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-5.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-3.jpg",
                "/images/sample-products/p1-4.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-2.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-5.jpg",
                "/images/sample-products/p1-6.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-1.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-7.jpg",
                "/images/sample-products/p1-8.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-3.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-10.jpg",
                "/images/sample-products/p1-3.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-4.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.jpg",
                "/images/sample-products/p1-5.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-5.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-7.jpg",
                "/images/sample-products/p1-9.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-4.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.jpg",
                "/images/sample-products/p1-10.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-3.jpg",
        },
        {
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.jpg",
                "/images/sample-products/p1-2.jpg",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-2.jpg",
        }
    ]
}

export default sampleData;