const sampleData = {
    products: [
        {
            id: "polo",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 10,
            isFeatured: true,
            banner: "banner-1.jpg",
        },
        {
            id: "polo-loc",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.png",
                "/images/sample-products/p1-2.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 15,
            isFeatured: true,
            banner: "banner-5.jpg",
        },
        {
            id: "polo-lopfr",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 0,
            isFeatured: true,
            banner: "banner-2.jpg",
        },
        {
            id: "polo-pfr",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.png",
                "/images/sample-products/p1-2.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 20,
            isFeatured: true,
            banner: "banner-1.jpg",
        },
        {
            id: "polo-yes",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 25,
            isFeatured: true,
            banner: "banner-3.jpg",
        },
        {
            id: "polo-topic",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.png",
                "/images/sample-products/p1-2.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 45,
            isFeatured: true,
            banner: "banner-4.jpg",
        },
        {
            id: "polo-zoro",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 2,
            isFeatured: true,
            banner: "banner-5.jpg",
        },
        {
            id: "polo-laci",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.png",
                "/images/sample-products/p1-2.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-4.jpg",
        },
        {
            id: "polo-lr",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-1.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-3.jpg",
        },
        {
            id: "polo-lopfrklog",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-2.jpg",
        },
        {
            id: "polo-lopfpfdsr",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-2.jpg",
        },
        {
            id: "polo-loplllkfr",
            name: "Polo Sporting Stretch Shirt",
            slug: "polo-sporting-stretch-shirt",
            category: "Men's Dress Shirt",
            description: "Classic Polo style with modern comfort",
            images: [
                "/images/sample-products/p1-2.png",
                "/images/sample-products/p1-1.png",
            ],
            price: "59.99",
            brand: "Polo",
            rating: "4.5",
            numReviews: 10,
            stock: 5,
            isFeatured: true,
            banner: "banner-2.jpg",
        }
    ]
}

export default sampleData;